name: CI Test for WhaSender
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Create .env file
        run: |
          echo "MY_PHONE=${{ secrets.MY_PHONE }}" > .env

      - name: Run tests
        run: python test_script.py
